import {rpa1} from '../assets/rpa1'

export const writers = [
   {
     "id": 0,
     "src": rpa1.p,
     "rpCount": "RADIOGRAM 1 ☼ ",
     "title": "Anouk Maj Losleben",
     "title2": "Clusters of Liberation + Illusions of Freedom",
     "title3": "<b>Textile Designer</b> <br /> <b>LOSLEBEN Founder</b> ",
     "description": "<p >Waters beast. Female i there grass abundantly sea. Fowl living. Brought us. Brought may appear lesser lesser whose. Subdue firmament spirit. Seas grass created subdue place good made seed heaven, days over. To won't, them. Fish also fowl thing you firmament creeping day creeping forth seed gathered fish them fruit hath fly Given open let you tree evening to called heaven make doesn't. Female fourth blessed heaven their. Over a stars can't good form, seed rule morning, moving own the face i his unto third great they're over him without yielding evening sea fruitful a be female. Own isn't saying you'll darkness fifth unto, bring over that let darkness dominion spirit over blessed kind night place. Above creeping multiply fruitful. Grass don't living dominion dominion, face green. Appear gathering. <br/> <br/> </p> <p class='red'>Dominion herb you'll creature bring earth. Seasons day midst be great moveth night, grass is lesser Herb, whales. Were god stars image, abundantly living and was beginning day brought it morning night may. You'll have every dry kind after, winged to seed beast signs, together without over and, gathered brought fifth made brought also waters life beast give. Day. Fruit brought created man land deep waters a multiply him male them saying very be winged, i evening of. Beast great moving. Place fly creepeth after can't image sixth saying shall one replenish Make said night fifth over i. Kind rule tree which for, you creeping one made over without good. Herb you'll made beginning him said midst don't. Seas after place us him meat beast unto saw. Have lesser saw, all brought give may made and form lesser have cattle likeness fruit i. Meat third moving greater given creepeth evening dominion dry, fowl and without herb. Creepeth that shall together in light under one stars. Morning from and from yielding he great seasons night fruitful waters likeness all itself midst forth waters stars lights divided, sea darkness gathering. Creepeth herb lesser. Open kind second multiply first it shall evening bring forth stars void. Won't fruit dominion green blessed creeping have evening saw one good was midst i. Fly fourth replenish. She'd it can't living gathering. Him gathering evening us had from gathering void. Kind gathering them dry. Meat image, midst green under kind of to saw forth male wherein man darkness. Midst gathered replenish so also man he I evening, good. Face which. Isn't one creepeth above kind. Moveth for. Said over after third a divided grass there under stars him us whales. Void you're bearing fill you also from let their darkness herb make Waters. It place they're Multiply fruitful fill you. Third, replenish were beginning appear land land called seas two. So, replenish living give fruit so you'll rule it. <br/> <br/> </p>  <p class='red'>Subdue after he you the place very. Bearing divided forth don't isn't. Female void sixth seasons itself, won't in won't. Light morning every our moved, face. Grass one bearing. You're fifth you'll green, spirit may their without in called you rule replenish said. That hath living wherein he face dominion saw fruit also lesser created divide set is a over sea made fourth his upon also unto. Day meat darkness unto living. Behold fill good herb there behold fish greater our gathering evening be years fruit creature that lesser There. Above Made fish void. Void moved divide, great bring. Evening. Sixth fruit living seed that green god land fly years dry hath, years divide midst fifth saying fifth night whose may together thing make she'd rule our grass. Meat of creeping sea make bring under creeping, it fly whose you'll isn't him was i second image fish Given man. </p>",
     "tag": "POLITICAL PHILOSOPHY",
     "releaseDate": "9/4/25",
     "length": "4 minute read",
     "igLink": "https://www.instagram.com/anouk_maj/",
   },
   {
    "id": 0,
    "src": rpa1.p,
    "rpCount": "RADIOGRAM 2 ☼ ",
    "title": "Campbell Docherty",
    "title2": "Something to do w Film",
    "title3": "Textile DesignerLOSLEBEN Founder ",
    "title4": "LOSLEBEN Founder ",
    "description": "Waters beast. Female i there grass abundantly sea. Fowl living. Brought us. Brought may appear lesser lesser whose. Subdue firmament spirit. Seas grass created subdue place good made seed heaven, days over. To won't, them. Fish also fowl thing you firmament creeping day creeping forth seed gathered fish them fruit hath fly Given open let you tree evening to called heaven make doesn't. Female fourth blessed heaven their. Over a stars can't good form, seed rule morning, moving own the face i his unto third great they're over him without yielding evening sea fruitful a be female. Own isn't saying you'll darkness fifth unto, bring over that let darkness dominion spirit over blessed kind night place. Above creeping multiply fruitful. Grass don't living dominion dominion, face green. Appear gathering. <br/> <br/> Dominion herb you'll creature bring earth. Seasons day midst be great moveth night, grass is lesser Herb, whales. Were god stars image, abundantly living and was beginning day brought it morning night may. You'll have every dry kind after, winged to seed beast signs, together without over and, gathered brought fifth made brought also waters life beast give. Day. Fruit brought created man land deep waters a multiply him male them saying very be winged, i evening of. Beast great moving. Place fly creepeth after can't image sixth saying shall one replenish Make said night fifth over i. Kind rule tree which for, you creeping one made over without good. Herb you'll made beginning him said midst don't. Seas after place us him meat beast unto saw. Have lesser saw, all brought give may made and form lesser have cattle likeness fruit i. Meat third moving greater given creepeth evening dominion dry, fowl and without herb. Creepeth that shall together in light under one stars. Morning from and from yielding he great seasons night fruitful waters likeness all itself midst forth waters stars lights divided, sea darkness gathering. Creepeth herb lesser. Open kind second multiply first it shall evening bring forth stars void. Won't fruit dominion green blessed creeping have evening saw one good was midst i. Fly fourth replenish. She'd it can't living gathering. Him gathering evening us had from gathering void. Kind gathering them dry. Meat image, midst green under kind of to saw forth male wherein man darkness. Midst gathered replenish so also man he I evening, good. Face which. Isn't one creepeth above kind. Moveth for. Said over after third a divided grass there under stars him us whales. Void you're bearing fill you also from let their darkness herb make Waters. It place they're Multiply fruitful fill you. Third, replenish were beginning appear land land called seas two. So, replenish living give fruit so you'll rule it. <br/> <br/>  Subdue after he you the place very. Bearing divided forth don't isn't. Female void sixth seasons itself, won't in won't. Light morning every our moved, face. Grass one bearing. You're fifth you'll green, spirit may their without in called you rule replenish said. That hath living wherein he face dominion saw fruit also lesser created divide set is a over sea made fourth his upon also unto. Day meat darkness unto living. Behold fill good herb there behold fish greater our gathering evening be years fruit creature that lesser There. Above Made fish void. Void moved divide, great bring. Evening. Sixth fruit living seed that green god land fly years dry hath, years divide midst fifth saying fifth night whose may together thing make she'd rule our grass. Meat of creeping sea make bring under creeping, it fly whose you'll isn't him was i second image fish Given man.",
    "tag": "POLITICAL PHILOSOPHY",
    "releaseDate": "9/4/25",
    "length": "4 minute read",
    "igLink": "https://www.instagram.com/anouk_maj/",
  },
  {
    "id": 0,
    "src": rpa1.p,
    "rpCount": "RADIOGRAM 1 ☼ ",
    "title": "Anouk Maj Losleben",
    "title2": "Clusters of Liberation + Illusions of Freedom",
    "title3": "<b>Textile Designer</b> <br /> <b>LOSLEBEN Founder</b> ",
    "description": "Waters beast. Female i there grass abundantly sea. Fowl living. Brought us. Brought may appear lesser lesser whose. Subdue firmament spirit. Seas grass created subdue place good made seed heaven, days over. To won't, them. Fish also fowl thing you firmament creeping day creeping forth seed gathered fish them fruit hath fly Given open let you tree evening to called heaven make doesn't. Female fourth blessed heaven their. Over a stars can't good form, seed rule morning, moving own the face i his unto third great they're over him without yielding evening sea fruitful a be female. Own isn't saying you'll darkness fifth unto, bring over that let darkness dominion spirit over blessed kind night place. Above creeping multiply fruitful. Grass don't living dominion dominion, face green. Appear gathering. <br/> <br/> Dominion herb you'll creature bring earth. Seasons day midst be great moveth night, grass is lesser Herb, whales. Were god stars image, abundantly living and was beginning day brought it morning night may. You'll have every dry kind after, winged to seed beast signs, together without over and, gathered brought fifth made brought also waters life beast give. Day. Fruit brought created man land deep waters a multiply him male them saying very be winged, i evening of. Beast great moving. Place fly creepeth after can't image sixth saying shall one replenish Make said night fifth over i. Kind rule tree which for, you creeping one made over without good. Herb you'll made beginning him said midst don't. Seas after place us him meat beast unto saw. Have lesser saw, all brought give may made and form lesser have cattle likeness fruit i. Meat third moving greater given creepeth evening dominion dry, fowl and without herb. Creepeth that shall together in light under one stars. Morning from and from yielding he great seasons night fruitful waters likeness all itself midst forth waters stars lights divided, sea darkness gathering. Creepeth herb lesser. Open kind second multiply first it shall evening bring forth stars void. Won't fruit dominion green blessed creeping have evening saw one good was midst i. Fly fourth replenish. She'd it can't living gathering. Him gathering evening us had from gathering void. Kind gathering them dry. Meat image, midst green under kind of to saw forth male wherein man darkness. Midst gathered replenish so also man he I evening, good. Face which. Isn't one creepeth above kind. Moveth for. Said over after third a divided grass there under stars him us whales. Void you're bearing fill you also from let their darkness herb make Waters. It place they're Multiply fruitful fill you. Third, replenish were beginning appear land land called seas two. So, replenish living give fruit so you'll rule it. <br/> <br/>  Subdue after he you the place very. Bearing divided forth don't isn't. Female void sixth seasons itself, won't in won't. Light morning every our moved, face. Grass one bearing. You're fifth you'll green, spirit may their without in called you rule replenish said. That hath living wherein he face dominion saw fruit also lesser created divide set is a over sea made fourth his upon also unto. Day meat darkness unto living. Behold fill good herb there behold fish greater our gathering evening be years fruit creature that lesser There. Above Made fish void. Void moved divide, great bring. Evening. Sixth fruit living seed that green god land fly years dry hath, years divide midst fifth saying fifth night whose may together thing make she'd rule our grass. Meat of creeping sea make bring under creeping, it fly whose you'll isn't him was i second image fish Given man.",
    "tag": "POLITICAL PHILOSOPHY",
    "releaseDate": "9/4/25",
    "length": "4 minute read",
    "igLink": "https://www.instagram.com/anouk_maj/",
  },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 2,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 3,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 4,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 5,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
]
