import { rp1 } from "../assets/rp1";
import { rp2 } from "../assets/rp2";
import {rpa1} from '../assets/rpa1'

export const djs = [
  {
    id: 0,
    type: "mix",
    src: rp1.p,
    rpCount: "RP1 ♪ ",
    "2ppSrc": rp1.pp,
    ipSrc: rp1.ip,
    title: '"games that touch the arts"',
    title2: "ubi",
    title3: "Musician",
    title4: "DJ ",
    title5: "exxtralife Founder",
    title6: "Developer ",
    description:
      "<b><i>ubi</i></b> sits and talks with us about his <b>inspirations, video game soundtracks and gives insight into his event organisation, EXXTRALIFE.</b> <br /><b><i>ubi</i></b> is a <b>musician and DJ</b>, as well as a <b>web developer</b> with strong design sensibilities, hailing from Ireland, now based in North London.",
    mixId: "https://d2rmb5ql8vpbx8.cloudfront.net/RP1-ubi.wav",
    djLink: "https://www.instagram.com/ubiifuruuu/",
    igLink: "https://www.instagram.com/p/DIEUV-QMOVw/?img_index=1",
    scLink: "http://soundcloud.com/radio_project/rp1-ubi-games-that-touch-the-arts",
    npLink: "https://www.ninaprotocol.com/releases/rp1-ubi-games-that-touch-the-arts",
    broadcastDate: "5/4/25 15:00",
    length: "(1 Hour 26 Minutes)",
    genre: "DIGITAL PUNK",
    url: "rp1-ubi",
    chapters: [
      { startTime: 0, title: "RADIO (a)" },
      { startTime: 1954, title: "PROJECT" },
      { startTime: 3276, title: "RADIO (b)" },
    ],
    tracklist: [
      { startTime: "0", title: "RADIO (a)" },
      { title: "B Rocka Intro", artist: "Brandy" },
      { title: "capsule rmx →", artist: "CAPSULE" },
      { title: "What You Waiting For?", artist: "Gwen Stefani" },
      { title: "The Enigma", artist: "Ingrate" },
      { title: "3.14159", artist: "Lexie Liu" },
      { title: "Body + Mind", artist: "Anz" },
      { title: "Rescue (tasfet_rmx)", artist: "Tasfet" },
      { title: "Television", artist: " A.G. Cook" },
      { title: "Slide In", artist: "Goldfrapp" },
      { title: "Boss", artist: "Tomoya Ohtani" },
      { title: "Androgynous Girls", artist: "Girls Aloud " },
      { title: "Took a Turn", artist: "loukeman" },
      { title: "Steppin' Out", artist: "kaskade" },
      { title: "Sofi Needs a Ladder", artist: "deadmau5" },
      { title: "UBER XL", artist: "BABYXSOSA, POLO PERKS <3 <3 <3" },
      { title: "UNRELEASED", artist: "edenplus" },
      {
        title: "Club Stranger (Nguzunguzu Remix)",
        artist: "Nguzunguzu, Jhene Aiko",
      },
      {
        title: "TF DUMMY NUMBER ZERO ZERO ZERO ZERO ZERO ZERO ZERO ZERO",
        artist: "Elysia Crampton",
      },
      { title: "Emiranda (break)", artist: "Emiranda" },

      { startTime: "1954", title: "PROJECT" },
      { title: "CCTV!?", artist: "" },
      { title: "Autechre's 8 Hour NTS Mix", artist: "" },
      { title: "Ubi loves Olivia Rodrigo's 'Sour'", artist: "" },
      { title: "Ecco2K's 'Black Boy' spurred change!?", artist: "" },
      { title: "Goated Video Game Compilations and OST's", artist: "" },
      { title: "French TV has the best music", artist: "" },
      { title: "Why is 'Mirror's Edge' so hard?", artist: "" },
      { title: "Electric + Acoustic = ...yeah?", artist: "" },
      { title: "Exxtralife (Origins and resident DJ's)", artist: "" },
      { title: "Ubi's Ideal Railway Redesign", artist: "" },
      { title: "Ranking Notorious Evil Organisations", artist: "" },
      { title: "Programmed Art", artist: "" },
      { title: "Ubi's Next Release!", artist: "" },

      { startTime: "3276", title: "RADIO (b)" },
      { title: "X My Heart", artist: "Regret" },
      { title: "Wunna", artist: "Gunna" },
      { title: "Alura", artist: "Sweet Trip" },
      { title: "Ready Set Go", artist: "Cedric Madden" },
      { title: "ginger candy", artist: "NEW YORK" },
      { title: "Dance Until We Die", artist: "A.G. Cook" },
      {
        title: "People Always Talk About The Weather (Junkie XL Main Mix)",
        artist: "Yonderboi",
      },
      { title: "When It's You", artist: "benoviolence" },
      { title: "dead long time", artist: "Nguzunguzu" },
      { title: "Overly", artist: "Playboi Carti" },
      { title: "Mr. Me Too", artist: "Clipse" },
      { title: "The Last One To Remain", artist: "Pandatone" },
      { title: "Leonora", artist: "Toxe" },
      { title: "cream", artist: "HIDE" },
      { title: "edenrepeat [u u u]", artist: "edenplus" },
    ],
  },
  {
    id: 1,
    type: "mix",
    src: rp2.p,
    rpCount: "RP2 ♪ ",
    "2ppSrc": rp2.pp,
    ipSrc: rp2.ip,
    title: '"BUILD!"',
    title2: "DVD",
    url: "rp2-dvd",
    title3: "Technologist",
    title4: "DJ",
    description:
      "<i><b>DVD</b></i> touches on <b>listening experiences; his introductions into tech; music and DJing; and his many creative design projects.</b><br/><br/> <i><b>DVD</b></i> is a <b>creative technologist and DJ</b> as well as a <b>audiophile,</b> versatile in soundsystem creation.",
    mixId: "https://d2rmb5ql8vpbx8.cloudfront.net/rp2-dvd.wav",
    djLink: "https://www.instagram.com/david.chen02/",
    igLink: "https://www.instagram.com/p/DI_inZws2SI/?img_index=1",
    scLink: "https://soundcloud.com/radio_project/rp2-dvd-build",
    npLink: "--",
    broadcastDate: "28/4/25 15:00",
    length: "1 Hour 26 Minutes",
    genre: "NEO JAZZ-FUNK REVIVAL",
    chapters: [
      { startTime: 0, title: "RADIO (a)" },
      { startTime: 1837, title: "PROJECT" },
      { startTime: 3334, title: "RADIO (b)" },
    ],
    tracklist: [
      { startTime: "0", title: "RADIO (a)" },
      { title: "Just A Touch (Jazz Element Mix)", artist: "Essence" },
      { title: "Love Will Bring Us Back Together", artist: "Roy Ayers" },
      { title: "Babalonia", artist: "Ricardo Marrero + The Group" },
      { title: "Rhythm In Your Mind", artist: "STR4TA, Steve Conry, Takashi Nakazato" },
      { title: "Love Is Gonna Lift You Up", artist: "Bobby Womack, Julio Bushmore" },
      { title: "Tied Up", artist: "Moon Boots, Steven Klavier, Kenny Dope" },
      { title: "Standing Right Here", artist: "Mannix, Dina Vass, John Morales" },
      { title: "The Calling", artist: "Ralf Gum, Joseph Junior" },
      { title: "Truth Don Die", artist: "Femi Kuti, Kerri Chandler" },
      { title: "Let the Sun Shine In", artist: "Sons and Daughters of Life" },
      

      { startTime: "1954", title: "PROJECT" },
      { title: "First Steps in Tech", artist: "" },
      { title: "DVD's Design Philosophy", artist: "" },
      { title: "Handle With Care!", artist: "" },
      { title: "Sound-System-Stack-Assembly", artist: "" },
      { title: "Searching for Nuts and Bolts", artist: "" },
      { title: "Don't Forget to Dance", artist: "" },
      { title: "KINDRED Listening Station", artist: "" },

      { startTime: "3276", title: "RADIO (b)" },
      { title: "Rise & Shine", artist: "Esteban Adame" },
      { title: "Birds, Pt. I", artist: "Chassol" },
      { title: "IM SO STUPID IM CLEVER", artist: "RAZA" },
      { title: "Love Is Forever", artist: "Blaze" },
      { title: "Babalonia", artist: "Ricardo Marrero + The Group" },
      { title: "Get You ", artist: "James Curd, Osunlade, Alton Miller" },
      {
        title: "Sunlight",
        artist: "Infiniti",
      },
      { title: "Emberfall", artist: "Loxodrome" },
      { title: "Souffles H", artist: "Kyoto Jazz Massive" },
      
    ],
  },
  //   {
  //   "id": 2,
  //   "type": "radiogram",
  //   "src": rpa1.p,
  //   "rpCount": "RADIOGRAM 1 ☼ ",
  //   "broadcastDate": "12/4/25 15:00",
  //   "url": "rg1-anouk-maj-losleben-clusters-of-liberation-illusions-of-freedom",
  //   "title2": "Anouk Maj Losleben",
  //   "title": "Clusters of Liberation + Illusions of Freedom",
  //   "title3": "Textile Designer",
  //   "title4": "LOSLEBEN Founder",
  //   "description": "<p><b>Freedom</b> is consumed under the pretence that it is unlimited; there is no such thing as being “too free”. Quite the contrary, <strong><b>freedom</b> is the ultimate end, the manifestation of the good, the absence of all evil.</strong> The happy man is free, the free man is happy. But the word <b>freedom</b> is to humans what the bell is for Pavlov’s dogs. We rarely question what <b>freedom</b> is, who provides it, or the cost that <b>freedom</b> is priced at. We indulge in it, consume it to its fullest, then cry for more. Like dogs, we eat what's served, beg for seconds, and thank our owner.<br/><br/> The advancement of industrialisation introduced capitalist ideologies, which ultimately aimed to increase economic productivity and expand possibilities for the individual. The free-market economy claimed to increase employment, social mobility, choice of goods, and education, and therefore sustain higher degrees of <b>freedom</b>, compared to the heavily constricting traditional class hierarchies of the pre-agricultural revolution. Its development has ultimately achieved the opposite; the subjugation of the individual into an economically productive tool that is utilised to serve as a means to the end of the dominating institutions. As H. Marcuse predicted in the 1950s, the advanced capitalist society that supposedly increases liberty due to its “non-interventionist” ideology, measures <b>freedom</b> through economic activity; the access to material goods and the possession thereof. The illusion of choice then projects <b>freedom</b>, but ultimately, <strong>the only <b>freedom</b> the individual is granted is committing to the same orders that sustain these oppressive economic structures.</strong> Critical immaterial properties that constitute <b>freedom</b>, such as rights, individuality, liberty of thought, and the expression thereof, may be met, but have lost their function in society. Rather, the extent to which the individual may participate unrestrictedly in the economy through the obtaining of monetary and material goods prevails over the essence of <b>freedom</b>.<br/><br/> Variety of choice has therefore become the ultimate quantification of <b>freedom</b>; how extensive is the pool of goods you can choose from, and how much of that can you call your own? If <b>freedom</b> is derived from the free-market, you must participate to claim this liberty. The culture of mass-consumption then illusions individuals to be free in the Western civilization, as they are flooded with choices of material goods. The equation is relatively simple: if the free market ensures your <b>freedom</b>, the more access you have, the greater your <b>freedom</b>. Therefore, needless variations of the same product are promoted, creating the illusion of innumerable choices to parallelly manifest unlimited <b>freedom</b>. Whilst individuals externalise <b>freedom</b> through the arbitrary choices made, their initial participation in the market was nothing but forced. <strong>It does not matter what choice is made, only that a choice is made, repeatedly, consistently, and frequently. The pressure to submit to mass-consumption is severe; advertisements are pushed constantly, products are too cheap, trends change weekly.</strong> Consumption of goods is centralised in the current means of existence, even if it’s inefficient or unproductive to the individual. Meanwhile, attention is sold as a commodity, and individuals will passively neglect demands for immaterial <b>freedoms</b>. “Independence of thought, autonomy, and the right to political opposition” are all properties that come at the cost of endless indulgence into consumption. The illusion of <b>freedom</b> through arbitrary choices keeps the people tamed, obedient, distracted. As long as they are sufficiently entertained, fed, and kept far enough from the ugly, no threat to those whose products are consumed is posed.<br/><br/> This sounds like a conspiracy theory. Because, ultimately, people still claim their immaterial <b>freedoms</b>; we protest, we complain, we educate ourselves. But the economic system establishes the realm within which the individual may exist without risking the status quo; <strong>you may be angry, as long as your anger does not threaten to destabilize the current structures.</strong> The change you may enact is through increased commitment to the same structures that subject you as a means to their end; political candidates, policy changes, all embodying the same economic structures, only varying versions thereof. Rational contention must occur through positive improvements of the same mechanisms that structure the economic system, which thereby strengthens itself through claiming higher satisfaction with the individual and gaining legitimacy. <strong>The individual is granted as much executive decision-making power that satisfies her own demand for believing to have agency over her life in the political sphere.</strong> The only power the individual truly possesses is her function as an economic subject, being a minor fragment of the larger unit. Effective protest can thus only be expressed through the aggravated rejection of this function. This is evident as through the newly introduced Anti-Boycott Bill, the individual is prohibited to even freely choose how to economically participate. The paradoxical nature of a free-market economy that prohibits free economic activity should illuminate a glimpse of how individual liberty is not the primary end of capitalism.<br/><br/><strong>We are convinced to be free, yet all fall victim to the traps of consumption.</strong> Alienated from our morality, we look past the horrors of production, the path to destruction we are firmly walking, and our own kind we are sacrificing on the way. Why can’t we stop buying iPhones or use Instagram? Why are we glued to a screen seven hours a day? Why do we own 21 different t-shirts? When it is so difficult to refuse to participate in useless consumption despite realising its harm, we must question its appeal to liberty. <strong>Consumption is intentional, just not by the consumer.</strong> If humanity is meant to be free in a free-market society, how have we become so passive?  </p>",
  //   "tag": "POLITICAL PHILOSOPHY",
  //   "releaseDate": "--/-/25",
  //   "length": "7 minute read",
  //   "igLink": "https://www.instagram.com/anouk_maj/",
  // }


  
];
