import { rp1 } from "../assets/rp1";

export const djs = [
  {
    id: 0,
    src: rp1.p,
    rpCount: "RP1 ♪ ",
    "2ppSrc": rp1.pp,
    ipSrc: rp1.ip,
    title: '"games that touch the arts"',
    title2: "ubi",
    title3: "Musician",
    title4: "DJ ",
    title5: "exxtralife Founder",
    title6: "Developer ",
    description:
      "<b><i>ubi</i></b> sits and talks with us about his <b>inspirations, video game soundtracks and gives insight into his event organisation, EXXTRALIFE.</b> <br /><br /><b><i>ubi</i></b> is a <b>musician and DJ</b>, as well as a <b>web developer</b> with strong design sensibilities, hailing from Ireland, now based in North London.",
    mixId: "https://d2rmb5ql8vpbx8.cloudfront.net/RP1-ubi.wav",
    djLink: "https://www.instagram.com/ubiifuruuu/",
    igLink: "--",
    scLink: "https://soundcloud.com/radio_project/rp1-ubiifuruuu",
    npLink: "--",
    broadcastDate: "5/4/25 15:00",
    length: "(1 Hour 26 Minutes)",
    genre: "ELECTRO-POP",
    chapters: [
      { startTime: 0, title: "RADIO (a)" },
      { startTime: 1954, title: "PROJECT" },
      { startTime: 3276, title: "RADIO (b)" },
    ],
    tracklist: [
      { startTime: "0", title: "RADIO (a)" },
      { title: "B Rocka Intro", artist: "Brandy" },
      { title: "capsule rmx →", artist: "CAPSULE" },
      { title: "What You Waiting For?", artist: "Gwen Stefani" },
      { title: "The Enigma", artist: "Ingrate" },
      { title: "3.14159", artist: "Lexie Liu" },
      { title: "Body + Mind", artist: "Anz" },
      { title: "Rescue (tasfet_rmx)", artist: "Tasfet" },
      { title: "Television", artist: " A.G. Cook" },
      { title: "Slide In", artist: "Goldfrapp" },
      { title: "Boss", artist: "Tomoya Ohtani" },
      { title: "Androgynous Girls", artist: "Girls Aloud " },
      { title: "Took a Turn", artist: "loukeman" },
      { title: "Steppin' Out", artist: "kaskade" },
      { title: "Sofi Needs a Ladder", artist: "deadmau5" },
      { title: "UBER XL", artist: "BABYXSOSA, POLO PERKS <3 <3 <3" },
      { title: "UNRELEASED", artist: "edenplus" },
      {
        title: "Club Stranger (Nguzunguzu Remix)",
        artist: "Nguzunguzu, Jhene Aiko",
      },
      {
        title: "TF DUMMY NUMBER ZERO ZERO ZERO ZERO ZERO ZERO ZERO ZERO",
        artist: "Elysia Crampton",
      },
      { title: "Emiranda (break)", artist: "Emiranda" },

      { startTime: "1954", title: "PROJECT" },
      { title: "CCTV!?", artist: "" },
      { title: "Autechre's 8 Hour NTS Mix", artist: "" },
      { title: "Ubi loves Olivia Rodrigo's 'Sour'", artist: "" },
      { title: "Ecco2K's 'Black Boy' spurred change!?", artist: "" },
      { title: "Goated Video Game Compilations and OST's", artist: "" },
      { title: "French TV has the best music", artist: "" },
      { title: "Why is 'Mirror's Edge' so hard?", artist: "" },
      { title: "Electric + Acoustic = ...yeah?", artist: "" },
      { title: "Exxtralife (Origins and resident DJ's)", artist: "" },
      { title: "Ubi's Ideal Railway Redesign", artist: "" },
      { title: "Ranking Notorious Evil Organisations", artist: "" },
      { title: "Programmed Art", artist: "" },
      { title: "Ubi's Next Release!", artist: "" },

      { startTime: "3276", title: "RADIO (b)" },
      { title: "X My Heart", artist: "Regret" },
      { title: "Wunna", artist: "Gunna" },
      { title: "Alura", artist: "Sweet Trip" },
      { title: "Ready Set Go", artist: "Cedric Madden" },
      { title: "ginger candy", artist: "NEW YORK" },
      { title: "Dance Until We Die", artist: "A.G. Cook" },
      {
        title: "People Always Talk About The Weather (Junkie XL Main Mix)",
        artist: "Yonderboi",
      },
      { title: "When It's You", artist: "benoviolence" },
      { title: "dead long time", artist: "Nguzunguzu" },
      { title: "Overly", artist: "Playboi Carti" },
      { title: "Mr. Me Too", artist: "Clipse" },
      { title: "The Last One To Remain", artist: "Pandatone" },
      { title: "Leonora", artist: "Toxe" },
      { title: "cream", artist: "HIDE" },
      { title: "edenrepeat [u u u]", artist: "edenplus" },
    ],
  },
];
