import { rp1 } from "../assets/rp1";
import { rp2 } from "../assets/rp2";
import { rp3 } from "../assets/rp3";
import { rp5 } from "../assets/rp5";
import { rpa1 } from '../assets/rpa1';
import { rpa2 } from '../assets/rpa2';
import { rpa3 } from '../assets/rpa3';
import { rpa4 } from '../assets/rpa4';
import { Radiogram1 } from '../components/radiograms/radiogram1/Radiogram1';
import { Radiogram2 } from '../components/radiograms/radiogram2/Radiogram2';
import { Radiogram3 } from '../components/radiograms/radiogram3/Radiogram3';
import { Radiogram4 } from '../components/radiograms/radiogram4/Radiogram4';
import { Radiogram5 } from '../components/radiograms/radiogram5/Radiogram5';
import { Radiogram6 } from '../components/radiograms/radiogram6/Radiogram6';
import { Radiogram7 } from '../components/radiograms/radiogram7/Radiogram7';


export const djs = [
  {
    id: 0,
    type: "mix",
    src: rp1.p,
    src3: rp1.pd,
    title: 'game arts',
    title2: "edenplus",
    title3: "exxtralife founder",
    description:
      "<a href='https://www.instagram.com/ubiifuruuu/' target='_blank'>EDENPLUS</a> sits and talks with us about his <b>inspirations, video game soundtracks</b> and gives insight into his event organisation, <b>EXXTRALIFE.</b>",
    mixId: "https://d2rmb5ql8vpbx8.cloudfront.net/RP1-ubi.wav",
    djLink: "https://www.instagram.com/ubiifuruuu/",
    igLink: "https://www.instagram.com/p/DIEUV-QMOVw/?img_index=1",
    scLink: "http://soundcloud.com/radio_project/rp1-ubi-games-that-touch-the-arts",
    npLink: "https://www.ninaprotocol.com/releases/rp1-ubi-games-that-touch-the-arts",
    broadcastDate: "5/4/25 15:00",
    releaseDate: "5/4/25",
    length: "(1 Hour 26 Minutes)",
    genre: "DIGITAL PUNK",
    url: "edenplus",
    chapters: [
      { startTime: 0, title: "RADIO (a)" },
      { startTime: 1954, title: "PROJECT" },
      { startTime: 3276, title: "RADIO (b)" },
    ],
    tracklist: [
      { startTime: "0", title: "RADIO (a)" },

      { title: "B Rocka Intro", artist: "Brandy" },
      { title: "capsule rmx →", artist: "CAPSULE" },
      { title: "What You Waiting For?", artist: "Gwen Stefani" },
      { title: "The Enigma", artist: "Ingrate" },
      { title: "3.14159", artist: "Lexie Liu" },
      { title: "Body + Mind", artist: "Anz" },
      { title: "Rescue (tasfet_rmx)", artist: "Tasfet" },
      { title: "Television", artist: " A.G. Cook" },
      { title: "Slide In", artist: "Goldfrapp" },
      { title: "Boss", artist: "Tomoya Ohtani" },
      { title: "Androgynous Girls", artist: "Girls Aloud " },
      { title: "Took a Turn", artist: "loukeman" },
      { title: "Steppin' Out", artist: "kaskade" },
      { title: "Sofi Needs a Ladder", artist: "deadmau5" },
      { title: "UBER XL", artist: "BABYXSOSA, POLO PERKS <3 <3 <3" },
      { title: "UNRELEASED", artist: "edenplus" },
      {
        title: "Club Stranger (Nguzunguzu Remix)",
        artist: "Nguzunguzu, Jhene Aiko",
      },
      {
        title: "TF DUMMY NUMBER ZERO ZERO ZERO ZERO ZERO ZERO ZERO ZERO",
        artist: "Elysia Crampton",
      },
      { title: "Emiranda (break)", artist: "Emiranda" },

      { startTime: "1954", title: "PROJECT" },

      { title: "CCTV!?", artist: "" },
      { title: "Autechre's 8 Hour NTS Mix", artist: "" },
      { title: "Ubi loves Olivia Rodrigo's 'Sour'", artist: "" },
      { title: "Ecco2K's 'Black Boy' spurred change!?", artist: "" },
      { title: "Goated Video Game Compilations and OST's", artist: "" },
      { title: "French TV has the best music", artist: "" },
      { title: "Why is 'Mirror's Edge' so hard?", artist: "" },
      { title: "Electric + Acoustic = ...yeah?", artist: "" },
      { title: "Exxtralife (Origins and resident DJ's)", artist: "" },
      { title: "Ubi's Ideal Railway Redesign", artist: "" },
      { title: "Ranking Notorious Evil Organisations", artist: "" },
      { title: "Programmed Art", artist: "" },
      { title: "Ubi's Next Release!", artist: "" },

      { startTime: "3276", title: "RADIO (b)" },
      { title: "X My Heart", artist: "Regret" },
      { title: "Wunna", artist: "Gunna" },
      { title: "Alura", artist: "Sweet Trip" },
      { title: "Ready Set Go", artist: "Cedric Madden" },
      { title: "ginger candy", artist: "NEW YORK" },
      { title: "Dance Until We Die", artist: "A.G. Cook" },
      {
        title: "People Always Talk About The Weather (Junkie XL Main Mix)",
        artist: "Yonderboi",
      },
      { title: "When It's You", artist: "benoviolence" },
      { title: "dead long time", artist: "Nguzunguzu" },
      { title: "Overly", artist: "Playboi Carti" },
      { title: "Mr. Me Too", artist: "Clipse" },
      { title: "The Last One To Remain", artist: "Pandatone" },
      { title: "Leonora", artist: "Toxe" },
      { title: "cream", artist: "HIDE" },
      { title: "edenrepeat [u u u]", artist: "edenplus" },
    ],
  },
  {
    id: 1,
    type: "mix",
    src: rp2.p,
    src3: rp2.pd,
    title: 'BUILD!',
    title2: "DVD",
    url: "dvd",
    title3: "Technologist",
    title4: "DJ",
    description:
      "<a href='https://www.instagram.com/david.chen02/' target='_blank'>DVD</a> touches on <b>listening experiences, his introductions into tech, music and DJing,</b> and his many <b>creative design projects</b>",
    mixId: "https://d2rmb5ql8vpbx8.cloudfront.net/rp2-dvd.wav",
    djLink: "https://www.instagram.com/david.chen02/",
    igLink: "https://www.instagram.com/p/DI_inZws2SI/?img_index=1",
    scLink: "https://soundcloud.com/radio_project/rp2-dvd-build",
    npLink: "https://www.ninaprotocol.com/releases/rp2-dvd-build",
    broadcastDate: "28/4/25 15:00",
    releaseDate: "28/4/25",
    length: "1 Hour 26 Minutes",
    genre: "NEO JAZZ-FUNK REVIVAL",
    chapters: [
      { startTime: 0, title: "RADIO (a)" },
      { startTime: 1837, title: "PROJECT" },
      { startTime: 3334, title: "RADIO (b)" },
    ],
    tracklist: [
      { startTime: "0", title: "RADIO (a)" },
      { title: "Just A Touch (Jazz Element Mix)", artist: "Essence" },
      { title: "Love Will Bring Us Back Together", artist: "Roy Ayers" },
      { title: "Babalonia", artist: "Ricardo Marrero + The Group" },
      { title: "Rhythm In Your Mind", artist: "STR4TA, Steve Conry, Takashi Nakazato" },
      { title: "Love Is Gonna Lift You Up", artist: "Bobby Womack, Julio Bushmore" },
      { title: "Tied Up", artist: "Moon Boots, Steven Klavier, Kenny Dope" },
      { title: "Standing Right Here", artist: "Mannix, Dina Vass, John Morales" },
      { title: "The Calling", artist: "Ralf Gum, Joseph Junior" },
      { title: "Truth Don Die", artist: "Femi Kuti, Kerri Chandler" },
      { title: "Let the Sun Shine In", artist: "Sons and Daughters of Life" },


      { startTime: "1954", title: "PROJECT" },
      { title: "First Steps in Tech", artist: "" },
      { title: "DVD's Design Philosophy", artist: "" },
      { title: "Handle With Care!", artist: "" },
      { title: "Sound-System-Stack-Assembly", artist: "" },
      { title: "Searching for Nuts and Bolts", artist: "" },
      { title: "Don't Forget to Dance", artist: "" },
      { title: "KINDRED Listening Station", artist: "" },

      { startTime: "3276", title: "RADIO (b)" },
      { title: "Rise & Shine", artist: "Esteban Adame" },
      { title: "Birds, Pt. I", artist: "Chassol" },
      { title: "IM SO STUPID IM CLEVER", artist: "RAZA" },
      { title: "Love Is Forever", artist: "Blaze" },
      { title: "Babalonia", artist: "Ricardo Marrero + The Group" },
      { title: "Get You ", artist: "James Curd, Osunlade, Alton Miller" },
      {
        title: "Sunlight",
        artist: "Infiniti",
      },
      { title: "Emberfall", artist: "Loxodrome" },
      { title: "Souffles H", artist: "Kyoto Jazz Massive" },

    ],
  },
  {
    "id": 2,
    "type": "radiogram",
    "src": rpa1.p,
    "src3": rpa1.pd,
    "rpCount": "RG1",
    "broadcastDate": "18/6/25 17:00",
    "broadcastDay": "18",
    "broadcastMonth": "06",
    "broadcastYear": "25",
    "broadcastTime": "17:00",
    "url": "anouk",
    "title2": "Anouk Losleben",
    "title": "The Promise of Freedom in the Western Sphere",
    "title3": "losleben founder",
    "description": Radiogram1,
    "tag": "Political Philosophy",
    "summary": "<span class='red'><a href='https://www.instagram.com/anouk_maj/' target='_blank'>ANOUK LOSLEBEN</a> writes that in today’s capitalist society, we’re made to believe we are free because we can choose things. But in reality, <b>we’re trapped in a system that uses consumption to control us and limit our true freedom.</b></span>",
    "releaseDate": "18/6/25",
    "length": "07:00",
    "igLink": "https://www.instagram.com/anouk_maj/",
    "postLink": "https://www.instagram.com/p/DLC1x7eN8Lr/?img_index=1",
  },
  {
    id: 3,
    type: "mix",
    src: rp3.p,
    src3: rp3.pd,
    title: 'Ghost in the Shell',
    title2: "BEBELUNA",
    url: "bebeluna",
    title3: "Musician",
    description:
      "<a href='https://www.instagram.com/itsbebeluna/ ' target='_blank'>BEBELUNA</a>, also known as <b><i>XYRAK47</i></b>, speaks about <b>her experience as a refugee in London and her love for composition in film and media.</b>",
    mixId: "https://d2rmb5ql8vpbx8.cloudfront.net/RP3-BEBE.wav",
    djLink: "https://www.instagram.com/itsbebeluna/",
    igLink: "https://www.instagram.com/p/DMh4aoKsARb/?img_index=1",
    scLink: "https://soundcloud.com/radio_project/rp3-bebeluna-gits",
    npLink: "https://www.ninaprotocol.com/releases/rp3-bebeluna-ghost-in-the-shell",
    broadcastDate: "25/7/25 15:00",
    releaseDate: "25/7/25",
    length: "1 Hour 26 Minutes",
    genre: "DIASPORIC BASS",
    chapters: [
      { startTime: 0, title: "RADIO (a)" },
      { startTime: 1871, title: "PROJECT" },
      { startTime: 3306, title: "RADIO (b)" },
    ],
    tracklist: [
      { startTime: "0", title: "RADIO (a)" },
      { title: "Hasta Santiago A Pie (Congas Orientales)", artist: "Los Hermanos Bravo" },
      { title: "Part Two (Release of the Moon)", artist: "Kit Gordon, Isaac Robertson" },
      { title: "Kulu", artist: "N'Gou Bagayoko" },
      { title: "Sunset Key Melt", artist: "Tim Hecker" },
      { title: "Both Sides Now", artist: "Joni Mitchell" },
      { title: "Su Pelo", artist: "Ray Heredia" },
      { title: "TDAGB", artist: "Duval Timothy" },
      { title: "Esperança", artist: "Munir Hossn, Ganavya" },


      { startTime: "1954", title: "PROJECT" },
      { title: "Life as a Refugee", artist: "" },
      { title: "Acoustic Tendencies", artist: "" },
      { title: "Vespa Life", artist: "" },
      { title: "Bebe's Experience Producing for Other Media Forms", artist: "" },
      { title: "Favourite Film Comps!?", artist: "" },
      { title: "The Cat Is In The Bag", artist: "" },

      { startTime: "3276", title: "RADIO (b)" },
      { title: "No Speaking (Breaka Remix)", artist: "Juice Menace" },
      { title: "Burn", artist: "REA" },
      { title: "Percussive Brain Cleanse", artist: "JOETI" },
      { title: "Butterfly (Kimboclat & Swerv Jersey Edit)", artist: "Crazy Town" },
      { title: "Night (Lucent Edit)", artist: "Benga & Coki" },
      { title: "Check Up On It (Edit)", artist: "Lo5ive" },
      {
        title: "1 Sec (Ali McK & IYZ Hard Re-Drum)",
        artist: "Novelist, Mumdance",
      },
      { title: "Lean Up", artist: "Sam Interface" },
      { title: "Conga Drive", artist: "Dilater" },
      { title: "Changes (MOOD$ Flip)", artist: "MOOD$" },
      { title: "Monica Belluci", artist: "Tom Manzarek" },
      { title: "fatfast", artist: "sanmallxxs" },
      { title: "Candy Drop", artist: "Disco Samir" },
      { title: "Grace (A.Fruit Remix)", artist: "Anna Morgan" },
      { title: "Juke It", artist: "Constantine, Sauadooble" },
      { title: "C-Slug", artist: "Muskila, HEDO HYDR8" },
      { title: "BANKHEAD (1-800-RAZ Remix)", artist: "KELELA" },
    ],
  },
  {

    "id": 4,
    "type": "radiogram",
    "src": rpa2.p,
    "src3": rpa2.pd,
    "broadcastDay": "18",
    "broadcastMonth": "08",
    "broadcastYear": "25",
    "broadcastTime": "17:00",
    "broadcastDate": "18/8/25",
    "url": "manny",
    "title2": "MANNY!",
    "title": "A Conversation with Manny",
    "title3": "Musician",
    "description": Radiogram2,
    "tag": "Religious Commentary",
    "summary": "<span><a href='https://www.instagram.com/radio__project/'>RADIO Project</a> spoke with <b>London-based pop artist</b></span> <a href='https://www.instagram.com/pattibobi/'>MANNY!</a><span> They spoke about the personal themes presented in his upcoming work and the space he has carved in music, defined by <b>honesty, experimentation, and an openness about faith, sexuality, and identity.</b></span>",
    "releaseDate": "18/8/25",
    "length": "05:30",
    "postLink": "https://www.instagram.com/p/DNfoIyhsIfG/?img_index=1",
    "igLink": "https://www.instagram.com/pattibobi/"
  },

  // UNPUBLISHED

  {
    id: 5,
    type: "mix",
    src: rp5.p,
    src3: rp5.pd,
    title: 'Kitbash',
    title2: "St. Michel",
    url: "stmichel",
    title3: "3d Designer",
    description:
      "<span><a href='https://www.instagram.com/radio__project/'>RADIO Project</a> spoke with </span> <a href='https://www.instagram.com/michael.adlj/'>St. Michel</a><span> about their journey as a 3D artist and how certain artists from the <b>early SoundCloud rap era influenced them.",
    mixId: "https://d2rmb5ql8vpbx8.cloudfront.net/rp3+total.wav",
    releaseDate: "5/2/26",
    length: "1 Hour 23 Minutes",
    genre: "AMBIENT TECHNO",
    chapters: [
      { startTime: 0, title: "RADIO (a)" },
      { startTime: 1672, title: "PROJECT" },
      { startTime: 3072, title: "RADIO (b)" },
    ],
    tracklist: [
      { startTime: "0", title: "RADIO (a)" },
      { title: "Any God Of Yours", artist: "Archy Marshall" },
      { title: "Moderato", artist: "Astrid Sonne" },
      { title: "Imposter", artist: "Oli XL" },
      { title: "Fullmoon (Motion Graphics Remix)", artist: "Ryuichi Sakamoto" },
      { title: "Soul", artist: "Stanisław Słowiński" },
      { title: "Moderato", artist: "Astrid Sonne" },
      { title: "Helm", artist: "Axis" },
      { title: "Merry Go Round", artist: "Bladee" },
      { title: "Just a Taste", artist: "Olivier Palfreyman" },
      { title: "Falaise", artist: "Floating Points" },

      { startTime: "1672", title: "PROJECT" },
      { title: "3D Beginnings", artist: "" },
      { title: "Analysing: Ash Thorp's McLaren 750S Premiere Video", artist: "" },
      { title: "The Marathon Scandal!?", artist: "" },
      { title: "The Origins of Whitelands!", artist: "" },
      { title: "That Feeling When Your Guitar String Snaps Mid Gig :(", artist: "" },
      { title: "We... know each other?", artist: "" },
      { title: "Biggest Mix/Production Inspirations", artist: "" },
      { title: "How Important The 2016 XXL Freshman Cypher Is/Was", artist: "" },
      { title: "Reptillian Club Boyz + The Tale of Hi-C", artist: "" },

      { startTime: "3072", title: "RADIO (b)" },
      { title: "E Like Energy", artist: "JKS" },
      { title: "Stay Tonight", artist: "Kruise Kontrol" },
      { title: "Reverie", artist: "DJ Sonnenbrand" },
      { title: "Fight", artist: "ADB" },
      { title: "Dune", artist: "Lysander" },
      { title: "Opener", artist: "Aiden Rudd" },
      {
        title: "Retrace",
        artist: "The Groove Room",
      },
      { title: "Night Division", artist: "Antigone" },
      { title: "Agora Mesmo", artist: "DJ Dextro" },
      { title: "Burnin", artist: "mischluft" },
      { title: "Generated Bounces", artist: "BXTR" },
      { title: "Flux", artist: "Chontane" },
      { title: "Race Against The Time (MRD Remix)", artist: "u.r.trax" },
      { title: "Truth Without Pain", artist: "Primal" }
    ],
    "dontShow": true,
  },
  {
    "id": 6,
    "type": "radiogram",
    "src": rpa4.p,
    "src2": rpa4.pm,
    "src3": rpa4.pd,
    "rpCount": "RG2 ",
    "broadcastDay": "18",
    "broadcastMonth": "08",
    "broadcastYear": "25",
    "broadcastTime": "17:00",
    "broadcastDate": "18/8/25",
    "url": "naja",
    "title2": "Naja",
    "title": "Proponent",
    "title3": "Writer + Curator",
    "description": Radiogram4,
    "tag": "creative writing",
    "summary": "<a href='https://www.instagram.com/https://www.instagram.com/najasurname/?hl=en/'>NAJA</a>'s essay, in three recollections, explores her sense of interconnections between <b>belief, death, and conspiracy. </b>",
    "releaseDate": "18/8/25",
    "length": "05:30",
    "postLink": "https://www.instagram.com/",
    "igLink": "https://www.instagram.com/najasurname/",
    "dontShow": true,
  },
  {
    "id": 7,
    "type": "radiogram",
    "src": rpa3.p,
    "src2": rpa3.pm,
    "src3": rpa3.pd,
    "rpCount": "RG2 ",
    "broadcastDay": "18",
    "broadcastMonth": "08",
    "broadcastYear": "25",
    "broadcastTime": "17:00",
    "broadcastDate": "18/8/25",
    "url": "andy",
    "title2": "Andy Xianyi Zhang",
    "title": "Walking Across Object Remains",
    "title3": "Director",
    "description": Radiogram5,
    "tag": "Film Commentary",
    "summary": "<span><a href='https://www.instagram.com/https://www.instagram.com/andydydydydydy/?hl=en/'>ANDY XIANYI ZHANG</a> revisits childhood Shanghai through Bunny Leap’s first music video, capturing memory and freedom by <b>walking through landscapes shaped bycontinuity.</b></span>",
    "releaseDate": "18/8/25",
    "length": "05:30",
    "postLink": "https://www.instagram.com/p/DNfoIyhsIfG/?img_index=1",
    "igLink": "https://www.instagram.com/pattibobi/",
    "dontShow": true,
  },
  
  
  {
    id: 8,
    "type": "radiogram",
    "src": rpa4.p,
    "src2": rpa4.pm,
    "src3": rpa4.pd,
    "rpCount": "RG2 ",
    "broadcastDay": "18",
    "broadcastMonth": "08",
    "broadcastYear": "25",
    "broadcastTime": "17:00",
    "broadcastDate": "18/8/25",
    "url": "edenplus2",
    "title2": "edenplus",
    "title": "article",
    "title3": "occupation",
    "description": Radiogram3,
    "tag": "music commentary",
    "summary": "summary",
    "releaseDate": "18/8/25",
    "length": "05:30",
    "postLink": "https://www.instagram.com/",
    "igLink": "https://www.instagram.com/ubifuruuu/",
    "dontShow": true,
  },
  {
    id: 9,
    "type": "radiogram",
    "src": rpa4.p,
    "src2": rpa4.pm,
    "src3": rpa4.pd,
    "rpCount": "RG2 ",
    "broadcastDay": "18",
    "broadcastMonth": "08",
    "broadcastYear": "25",
    "broadcastTime": "17:00",
    "broadcastDate": "18/8/25",
    "url": "thenarrator",
    "title2": "The Narrator",
    "title": "Love Is a Contact Sport",
    "title3": "occupation",
    "description": Radiogram6,
    "tag": "storytelling",
    "summary": "v1.1",
    "releaseDate": "18/8/25",
    "length": "05:30",
    "postLink": "https://www.instagram.com/",
    "igLink": "https://www.instagram.com/thenarrator_______/",
    "dontShow": true,

  },
  {
    id: 10,
    "type": "radiogram",
    "src": rpa4.p,
    "src2": rpa4.pm,
    "src3": rpa4.pd,
    "rpCount": "RG2 ",
    "broadcastDay": "18",
    "broadcastMonth": "08",
    "broadcastYear": "25",
    "broadcastTime": "17:00",
    "broadcastDate": "18/8/25",
    "url": "ivory",
    "title2": "Ivory Pijin",
    "title": "USB City",
    "title3": "occupation",
    "description": Radiogram7,
    "tag": "cultural commentary",
    "summary": "v1.1",
    "releaseDate": "18/8/25",
    "length": "05:30",
    "postLink": "https://www.instagram.com/",
    "igLink": "https://www.instagram.com/ivorypijin/",
    "dontShow": true,
  },

];
