export default {
  name: 'radiogram',
  title: 'Radiogram',
  type: 'document',
  fields: [
    { name: 'title', title: 'Article Title', type: 'string' },
    { name: 'authorName', title: 'Author Name', type: 'string' },
    { name: 'authorRole', title: 'Author Role', type: 'string', description: 'e.g. "Textile Designer", "Writer + Curator"' },
    { name: 'subtitle', title: 'Subtitle', type: 'string', description: 'e.g. "Essay by", "Responses from"' },
    {
      name: 'slug',
      title: 'URL Slug',
      type: 'slug',
      description: 'Must match the key in radiogramMap.js (e.g. "anouk", "manny")',
      options: { source: 'authorName' },
    },
    {
      name: 'rpCount',
      title: 'RP Count Label',
      type: 'string',
      description: 'e.g. "RG1", "RG2"',
    },
    { name: 'coverImage', title: 'Cover Image', type: 'image' },
    { name: 'coverImageMobile', title: 'Cover Image (Mobile)', type: 'image' },
    { name: 'coverImageDesktop', title: 'Cover Image (Desktop)', type: 'image' },
    { name: 'tag', title: 'Tag (single display)', type: 'string', description: 'e.g. "Political Philosophy"' },
    {
      name: 'tags',
      title: 'Tags',
      type: 'array',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    },
    {
      name: 'hexCodes',
      title: 'Hex Codes',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Exactly 2 hex colours — foreground and background',
      validation: (Rule) => Rule.max(2),
    },
    {
      name: 'summary',
      title: 'Summary',
      type: 'array',
      of: [{ type: 'block', styles: [], lists: [] }],
      description: 'Short preview shown on cards. Use bold for names and key phrases.',
    },
    { name: 'releaseDate', title: 'Release Date', type: 'date' },
    {
      name: 'broadcastDate',
      title: 'Broadcast Date',
      type: 'datetime',
      description: 'Full broadcast datetime',
    },
    { name: 'length', title: 'Read Time', type: 'string', description: 'e.g. "7 Minute Read"' },
    { name: 'postLink', title: 'Post Link (Instagram)', type: 'url' },
    { name: 'igLink', title: 'Author Instagram', type: 'url' },
    {
      name: 'dontShow',
      title: 'Hidden',
      type: 'boolean',
      description: 'Hide this item from the site',
      initialValue: false,
    },
  ],
  preview: {
    select: { title: 'authorName', subtitle: 'title', media: 'coverImage' },
  },
  orderings: [
    {
      title: 'Release Date',
      name: 'releaseDateDesc',
      by: [{ field: 'releaseDate', direction: 'desc' }],
    },
  ],
}
