import {rpa1} from './assets/rpa1'

export const writers = [
   {
     "id": 0,
     "src": rpa1.p,
     "rpCount": "RPA1 ♪ ",
     "title": "Anouk Losleben",
     "title2": "\"Anouk's Article\"",
     "title3": "<b>Textile Designer</b> ",
     "description": "article 1.",
   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 2,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 3,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 4,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 5,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
//   {
//     "id": 1,
//     "src": rpa1.p,
//     "rpCount": "RPA2 ♪ ",
//     "title": "Campbell Docherty",
//     "title2": "\"Campbell's Article\"y",
//     "title3": "<b>Developer</b> ",
//     "description": "article 2.",
//   },
]
